# Generated by Django 4.2 on 2023-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=25)),
                ('stufee', models.IntegerField()),
                ('stuaddress', models.CharField(max_length=50)),
                ('stumobile', models.CharField(max_length=20)),
                ('stubgrp', models.CharField(max_length=3)),
            ],
        ),
    ]
