# Generated by Django 4.2 on 2023-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clid', models.IntegerField()),
                ('clname', models.CharField(max_length=25)),
                ('clquote', models.IntegerField()),
                ('cleval', models.CharField(max_length=2)),
                ('clcountry', models.CharField(max_length=25)),
            ],
        ),
    ]
