# Generated by Django 4.2 on 2023-04-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
