# Generated by Django 4.2 on 2023-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empgrade',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
