# Generated by Django 4.2 on 2023-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_employee_empgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clid', models.IntegerField()),
                ('clname', models.CharField(max_length=25)),
                ('clquote', models.IntegerField()),
                ('cleval', models.CharField(max_length=2)),
                ('clcountry', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='empname',
            field=models.CharField(max_length=25),
        ),
    ]
