# Generated by Django 4.2 on 2023-04-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_clients_alter_employee_empname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
